### ISSUE TITLE
Add `flix.toml`?

### ISSUE THREAD

**Issue by magnus-madsen** [stephentetley/interop-base#1]
Let me propose to add a `flix.toml` file with:

```toml
[package]
name        = "interop-base"
description = "Low level Flix wrappers over classes and interfaces in the JDK."
version     = "1.0.0"
flix        = "0.34.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <email@example.com>"]
```

Then create a GitHub release (easy using the UI) with two files attached: the above `flix.toml` plus the output of `build-pkg`.

then to `basis-base` you can add another `flix.toml` with:

```toml
[package]
name        = "basis-base"
description = "Flix wrappers over the JDK built on interop-base."
version     = "1.0.0"
flix        = "0.34.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <email@example.com>"]

[dependencies]
"github:stephentetley/interop-base"              = "1.0.0"
```

and it should be able to automatically retrieve the dependency and place it into `lib`. 

This works whether you run Flix from the command line or from VSCode.

A working example is here:

- https://github.com/flix/museum
- https://github.com/flix/museum/blob/master/flix.toml

You can create an example that depends on museum if you want to experiment:

```toml
[dependencies]
"github:flix/museum"              = "1.2.0"
```

Caveats:

- We currently hit the GitHub API even when the files are already downloaded. Do this enough and you hit the rate limiter. This should be fixed this week. 
- Flix will read the `flix.toml` file and retrieve the dependencies (transitively, including maven dependencies) and put them into `lib`. However, it will never delete anything from `lib` so you must manage that yourself. (For example when upgrading a version).

Feel free to close / delete this ticket once you have seen it :) I just wanted to let you know.
